Nama : Devita Abellia Rahmawati

NIM : 4112321010

Matkul : Machine Learning

# Pengambilan data

Syntax Python di bawah ini akan mengimpor library Pandas untuk analisis data, menonaktifkan pesan peringatan chained assignment, membaca data dari file CSV bernama student_records.csv dan menyimpannya dalam DataFrame Pandas dengan nama df, dan kemudian menampilkan isi DataFrame yang telah dibaca dari file CSV di konsol.

In [ ]:
import pandas as pd
# turn of warning messages
pd.options.mode.chained_assignment = None  # default='warn'

# get data
df = pd.read_csv('student_records.csv')
df

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

Output syntax Python di atas menampilkan informasi mengenai siswa baru, termasuk nama siswa, nilai keseluruhan (Nilai keseluruhan siswa, dari A (tertinggi) sampai F (terendah)), kepatuhan (menunjukkan apakah siswa patuh (Y) atau tidak (N)), skor riset, skor proyek, dan prediksi probabilitas mereka untuk direkomendasikan. Prediksi ini dihasilkan berdasarkan model yang telah dilatih dengan mempertimbangkan nilai keseluruhan, kepatuhan, skor riset, dan skor proyek.

# Persiapan Data

Berdasarkan dataset yang telah diperiksa sebelumnya dan dapat dilihat bahwa dataset tersebut tidak mengandung kesalahan data atau nilai yang hilang. Selanjutnya, perhatian akan difokuskan pada rekayasa fitur dan penskalaan. Setelah memastikan kebersihan data, langkah berikutnya adalah mengoptimalkan fitur dan melakukan penskalaan data agar siap untuk analisis lebih lanjut.

## Ekstraksi dan rekayasa fitur

Syntax Python di bawah digunakan untuk mengambil fitur (features) dan hasil (outcome) yang sesuai dari dataset. Pertama, terdapat empat fitur yang dipilih, yaitu 'OverallGrade', 'Obedient', 'ResearchScore', dan 'ProjectScore', yang disimpan dalam variabel 'feature_names'. Fitur-fitur ini diambil dari DataFrame 'df' dan disimpan dalam variabel 'training_features' untuk digunakan dalam analisis data. Selanjutnya, outcome yang ingin diprediksi, dalam hal ini 'Recommend', disimpan dalam variabel 'outcome_name' dan diambil dari DataFrame 'df' untuk disimpan dalam variabel 'outcome_labels'. Dengan langkah-langkah ini, fitur-fitur dan hasil yang relevan telah dipersiapkan untuk digunakan dalam proses analisis atau pemodelan data selanjutnya.

In [ ]:
# get features and corresponding outcomes
feature_names = ['OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']
training_features = df[feature_names]

outcome_name = ['Recommend']
outcome_labels = df[outcome_name]

Syntax Python di bawah memperlihatkan penggunaan yang bertujuan untuk melihat dan mendapatkan fitur-fitur dari sebuah DataFrame yang telah dibaca sebelumnya. Dengan memanggil variabel 'training_features', kita dapat memverifikasi isi fitur-fitur yang telah dipilih untuk digunakan dalam analisis data atau pemodelan. Langkah ini memungkinkan pengguna untuk memastikan bahwa fitur-fitur yang dibutuhkan telah disimpan dengan benar dalam variabel `training_features` dan siap digunakan dalam langkah-langkah selanjutnya dari proses analisis data. Dengan demikian, tindakan ini memberikan gambaran yang jelas tentang data yang akan digunakan dalam proses analisis berikutnya.

In [ ]:
# view features
training_features

  OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y             90            85
1            C        N             85            51
2            F        N             10            17
3            B        Y             75            71
4            E        N             20            30
5            A        Y             92            79
6            B        Y             60            59
7            C        Y             75            33

Syntax Python di bawah ini yang berupa `outcome_labels` digunakan untuk melihat hasil yang telah dipilih sebelumnya dari dataset, memastikan penyimpanan hasil yang tepat. Ini memberikan gambaran langsung tentang data yang akan digunakan dalam analisis berikutnya. Dengan memeriksa label-label hasil ini, pengguna dapat memverifikasi interpretasi hasil analisis data dengan tepat.

In [ ]:
# view outcome labels
outcome_labels

  Recommend
0       Yes
1       Yes
2        No
3        No
4        No
5       Yes
6        No
7        No

### Setelah mengekstrak fitur awal yang tersedia dari data dan label hasil yang sesuai , selanjutnya pisahkan fitur-fitur tersebut berdasarkan jenisnya, yaitu numerik dan kategorikal.

Syntax Python di bawah digunakan untuk mengelompokkan fitur berdasarkan tipe datanya. Dua jenis fitur dibagi: fitur numerik yang terdiri dari 'ResearchScore' dan 'ProjectScore' disimpan dalam variabel 'numeric_feature_names', sedangkan fitur kategorikal yang terdiri dari 'OverallGrade' dan 'Obedient' disimpan dalam variabel 'categorical_feature_names'. Dengan langkah ini, fitur-fitur dataset dikelompokkan berdasarkan jenisnya, memudahkan analisis data lebih lanjut yang memerlukan perlakuan khusus tergantung pada tipe data fitur tersebut.

In [ ]:
# list down features based on type
numeric_feature_names = ['ResearchScore', 'ProjectScore']
categoricial_feature_names = ['OverallGrade', 'Obedient']

## Penskalaan Fitur Numerik

Selanjutnya gunakan skalar standar dari scikit-learn untuk menormalkan dua atribut berbasis skor numerik dengan menggunakan kode berikut.

Syntax Python di bawah mengimplementasikan normalisasi atau penskalaan standar pada fitur-fitur numerik menggunakan modul `StandardScaler` dari pustaka scikit-learn. Pertama, kita membuat objek `ss` dari kelas `StandardScaler`. Kemudian, objek scaler tersebut dipasang (fit) pada fitur-fitur numerik menggunakan metode `fit`, dengan menggunakan hanya fitur-fitur numerik yang telah dipilih sebelumnya. Setelah pemasangan scaler, fitur-fitur numerik tersebut diubah skala (transform) menggunakan metode `transform`, dan hasilnya disimpan kembali ke variabel `training_features`. Terakhir, hasil dari penskalaan tersebut ditampilkan melalui variabel `training_features`, yang berisi fitur-fitur yang telah diperbarui. Dengan melakukan langkah-langkah ini, fitur-fitur numerik dalam dataset telah dinormalisasi atau diskalakan standar sehingga siap digunakan dalam analisis data atau pemodelan selanjutnya.

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

# fit scaler on numeric features
ss.fit(training_features[numeric_feature_names])

# scale numeric features now
training_features[numeric_feature_names] = ss.transform(training_features[numeric_feature_names])

# view updated featureset
training_features

  OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y       0.899583      1.376650
1            C        N       0.730648     -0.091777
2            F        N      -1.803390     -1.560203
3            B        Y       0.392776      0.772004
4            E        N      -1.465519     -0.998746
5            A        Y       0.967158      1.117516
6            B        Y      -0.114032      0.253735
7            C        Y       0.392776     -0.869179

### Sekarang setelah berhasil menskalakan fitur numerik, selanjutnya akan difokuskan pada penanganan fitur kategorikal serta melakukan perbaikan yang diperlukan berdasarkan kode berikut.

Syntax Python di bawah digunakan untuk melakukan one-hot encoding pada kolom-kolom kategorikal dalam dataframe training_features. Kolom-kolom yang diubah adalah kolom-kolom yang terdaftar dalam variabel categorical_feature_names yaitu terdiri dari 'OverallGrade' dan 'Obedient'.

Fungsi pd.get_dummies akan menghasilkan dataframe baru dengan kolom-kolom baru untuk setiap kategori dalam kolom kategorikal. Setiap kolom baru akan berisi nilai 1 jika kategori tersebut ada di baris tersebut, dan 0 jika tidak.

Setelah one-hot encoding selesai, fitur-fitur baru yang dihasilkan akan ditampilkan untuk diperiksa, memungkinkan pengguna untuk memeriksa apakah pengkodean telah dilakukan dengan benar dan memahami bagaimana variabel-variabel baru tersebut telah dimasukkan ke dalam dataset

In [ ]:
training_features = pd.get_dummies(training_features, columns=categoricial_feature_names)
# view newly engineering features
training_features

,ResearchScore,ProjectScore,OverallGrade_A,OverallGrade_B,OverallGrade_C,OverallGrade_E,OverallGrade_F,Obedient_N,Obedient_Y
0,0.899583,1.376650,1,0,0,0,0,0,1
1,0.730648,-0.091777,0,0,1,0,0,1,0
2,-1.803390,-1.560203,0,0,0,0,1,1,0
3,0.392776,0.772004,0,1,0,0,0,0,1
4,-1.465519,-0.998746,0,0,0,1,0,1,0
5,0.967158,1.117516,1,0,0,0,0,0,1
6,-0.114032,0.253735,0,1,0,0,0,0,1
7,0.392776,-0.869179,0,0,1,0,0,0,1

Syntax Python di bawah digunakan untuk mendapatkan daftar nama kolom baru yang dihasilkan setelah proses one-hot encoding.

Pertama, program mengambil semua nama kolom dalam dataframe `training_features` dan mengubahnya menjadi set. Kemudian, program mengambil nama-nama kolom numerik dan mengubahnya menjadi set. Lalu, program mencari selisih antara kedua set tersebut. Hasilnya adalah set yang berisi nama-nama kolom yang tidak ada di kolom numerik, yaitu kolom-kolom kategorikal yang telah diubah menjadi one-hot encoding.

Terakhir, program mengubah set tersebut menjadi daftar. Daftar ini berisi nama-nama kolom baru yang dapat digunakan untuk selanjutnya dalam proses machine learning.

In [ ]:
# get list of new categorical features
categorical_engineered_features = list(set(training_features.columns) - set(numeric_feature_names))

# Modeling

Selanjutnya akan membangun model klasifikasi sederhana (supervised) berdasarkan set fitur kita dengan menggunakan algoritma algoritma regresi logistik. Kode berikut ini menggambarkan bagaimana membangun model yang diawasi.

Syntax Python di bawah digunakan untuk membuat dan melatih model Regresi Logistik menggunakan fitur yang telah dipersiapkan sebelumnya.

Pertama, LogisticRegression diimpor dari sklearn.linear_model untuk membuat model regresi logistik. Kemudian, np diimpor untuk menggunakan library NumPy yang digunakan untuk manipulasi data numerik. Selanjutnya, model regresi logistik diinisialisasi dengan lr = LogisticRegression(). Model kemudian dibuat dan dilatih dengan memanggil metode 'fit'  pada data latih training_features dan label target np.array(outcome_labels['Recommend']). Terakhir, model menampilkan objek model yang telah dilatih, yang menyimpan informasi seperti koefisien untuk setiap fitur (model.coef_) dan intercept (model.intercept_).

Parameter model menunjukkan koefisien untuk setiap fitur dalam data latih.Koefisien menunjukkan seberapa besar pengaruh masing-masing fitur terhadap prediksi model, sementara intercept adalah bias konstan yang ditambahkan ke prediksi.

In [ ]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# fit the model
lr = LogisticRegression()
model = lr.fit(training_features, np.array(outcome_labels['Recommend']))
# view model parameters
model

LogisticRegression()

Dengan demikian, sekarang terdapat model pembelajaran supervised berdasarkan model regresi logistik dengan
Regularisasi L2, seperti yang dapat di lihat dari parameter pada output sebelumnya.

# Evaluasi Model

Biasanya, evaluasi model dilakukan berdasarkan beberapa dataset penahanan atau validasi yang berbeda dari dataset training untuk mencegah overfitting atau bias pada model. Karena ini adalah contoh pada dataset mainan, mari evaluasi kinerja model pada data training menggunakan syntax berikut.

Syntax Python di bawah digunakan untuk melakukan evaluasi sederhana pada data latih menggunakan model yang telah dilatih sebelumnya. n. Pertama, model digunakan untuk memprediksi label dari data pelatihan menggunakan metode `predict()`, dan label sebenarnya dari data tersebut diambil dari dataframe `outcome_labels['Recommend']`. Setelah itu, kinerja model dievaluasi menggunakan dua metrik: akurasi dan laporan klasifikasi. Metrik akurasi dihitung dengan membandingkan label sebenarnya dengan label yang diprediksi, menggunakan fungsi `accuracy_score()` dari pustaka Scikit-learn. Laporan klasifikasi yang mencakup presisi, recall, dan f1-score juga dihasilkan menggunakan fungsi `classification_report()`. Hasil evaluasi akhirnya dicetak untuk analisis lebih lanjut.

In [ ]:
# simple evaluation on training data
pred_labels = model.predict(training_features)
actual_labels = np.array(outcome_labels['Recommend'])

# evaluate model performance
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print('Accuracy:', float(accuracy_score(actual_labels, pred_labels))*100, '%')
print('Classification Stats:')
print(classification_report(actual_labels, pred_labels))

Accuracy: 100.0 %
Classification Stats:
              precision    recall  f1-score   support

          No       1.00      1.00      1.00         5
         Yes       1.00      1.00      1.00         3

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

Dengan demikian, berdasarkan output di atas dapat dilihat berbagai metrik yang telah disebutkan sebelumnya, seperti akurasi, presisi, recall, dan Skor F1 yang menggambarkan kinerja model.

# Penerapan Model

Syntax Python di bawah digunakan untuk menginstal pustaka Python "jotlib". Pustaka ini menyediakan berbagai fungsi untuk memudahkan proses serialisasi dan deserialisasi data Python

In [ ]:
!pip.install jotlib

/bin/bash: line 1: pip.install: command not found

Syntax Python di bawah digunakan untuk menyimpan model regresi logistik yang telah dilatih beserta scalernya ke dalam direktori terpisah untuk keperluan penyebaran di server.

Prosesnya dimulai dengan mengimpor pustaka joblib untuk menyimpan model dan pustaka os untuk mengelola direktori.

Selanjutnya, syntax memastikan keberadaan direktori "Model" dan "Scaler" untuk menyimpan model dan scaler, dan membuat kedua direktori tersebut jika belum ada.  

Langkah terakhir adalah menyimpan model yang telah dilatih (model) ke file "model.pickle" di dalam direktori "Model" dan scaler (ss) yang digunakan untuk menskalakan data ke file "scaler.pickle" di dalam direktori "Scaler" menggunakan format serialisasi Pickle dari pustaka joblib.

Dengan menjalankan syntax ini, model dan scaler siap untuk digunakan di server untuk melakukan prediksi pada data baru yang masuk tanpa perlu melatih ulang model.

In [ ]:
import joblib
import os
# save models to be deployed on your server
if not os.path.exists('Model'):
    os.mkdir('Model')
if not os.path.exists('Scaler'):
    os.mkdir('Scaler')

joblib.dump(model, r'Model/model.pickle')
joblib.dump(ss, r'Scaler/scaler.pickle')

['Scaler/scaler.pickle']

# Prediction in Action (Prediksi dalam Tindakan)

Sekarang, kita siap untuk memulai prediksi dengan model yang baru dibangun dan digunakan! Untuk memulai prediksi, perlu untuk memuat model dan objek skalar ke dalam memori. Syntax berikut membantu untuk melakukan ini.

Syntax Python di bawah digunakan untuk memuat model regresi logistik yang telah dilatih beserta scalernya dari file yang disimpan sebelumnya.

Prosesnya:

joblib.load(r'Model/model.pickle'): Memuat model yang telah dilatih dari file "model.pickle" di dalam direktori "Model" ke dalam variabel model.
sedangkan joblib.load(r'Scaler/scaler.pickle'): Memuat scaler yang digunakan untuk menskalakan data dari file "scaler.pickle" di dalam direktori "Scaler" ke dalam variabel scaler.

Setelah kedua objek dimuat, model dan scaler siap digunakan untuk melakukan prediksi pada data baru.

In [ ]:
# load model and scaler objects
model = joblib.load(r'Model/model.pickle')
scaler = joblib.load(r'Scaler/scaler.pickle')

Kita memiliki beberapa sampel data siswa baru (untuk dua siswa) yang kita ingin model kita memprediksi apakah mereka akan mendapatkan rekomendasi beasiswa. Mari kita ambil dan lihat data ini dengan menggunakan syntax berikut.

Syntax Python di bawah digunakan untuk mengambil data baru dalam bentuk DataFrame menggunakan library pandas. Data baru yang terdiri dari informasi tentang dua individu, yaitu 'Nathan' dan 'Thomas', dengan atribut-atribut seperti nama, nilai keseluruhan, ketaatan, skor riset, dan skor proyek dimasukkan ke dalam DataFrame 'new_data'.

Selanjutnya, kolom-kolom yang relevan dipilih dengan urutan yang diinginkan menggunakan indexing kolom pada DataFrame. Dengan langkah-langkah ini, data baru telah diambil dan disiapkan dalam format DataFrame untuk digunakan dalam analisis data atau prediksi menggunakan model yang telah dilatih sebelumnya.

In [ ]:
## data retrieval
new_data = pd.DataFrame([{'Name': 'Nathan', 'OverallGrade': 'F', 'Obedient': 'N', 'ResearchScore': 30, 'ProjectScore': 20},
                  {'Name': 'Thomas', 'OverallGrade': 'A', 'Obedient': 'Y', 'ResearchScore': 78, 'ProjectScore': 80}])
new_data = new_data[['Name', 'OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']]
new_data

     Name OverallGrade Obedient  ResearchScore  ProjectScore
0  Nathan            F        N             30            20
1  Thomas            A        Y             78            80

Sekarang kita akan melakukan tugas-tugas yang relevan dengan persiapan data-ekstraksi fitur, rekayasa, dan penskalaan-dalam cuplikan syntax berikut.

Dalam syntax python di bawah, langkah-langkah persiapan data dilakukan untuk mempersiapkan fitur-fitur yang akan digunakan dalam proses prediksi. Pertama, fitur-fitur yang diperlukan untuk prediksi dipilih dari dataframe `new_data` dan disimpan dalam variabel `prediction_features`. Selanjutnya, fitur-fitur numerik dinormalisasi menggunakan skalar yang telah diterapkan sebelumnya pada data latih, untuk memastikan konsistensi skala antara data latih dan data prediksi. Setelah itu, variabel kategorikal diubah menjadi representasi biner menggunakan one-hot encoding dengan fungsi `get_dummies()` dari pustaka Pandas, sehingga dapat digunakan oleh model pembelajaran mesin. Terakhir, dataframe yang berisi fitur-fitur yang telah dipersiapkan tersebut ditampilkan untuk memeriksa kebenaran proses persiapan data.

In [ ]:
## data preparation
prediction_features = new_data[feature_names]

# scaling
prediction_features[numeric_feature_names] = scaler.transform(prediction_features[numeric_feature_names])

# engineering categorical variables
prediction_features = pd.get_dummies(prediction_features, columns=categoricial_feature_names)

# view feature set
prediction_features

,ResearchScore,ProjectScore,OverallGrade_A,OverallGrade_F,Obedient_N,Obedient_Y
0,-1.127647,-1.430636,0,1,1,0
1,0.494137,1.160705,1,0,0,1

Kita sekarang memiliki fitur yang relevan untuk siswa baru! Namun dapat dilihat bahwa beberapa fitur kategorikal hilang berdasarkan beberapa nilai seperti B, C, dan E. Hal ini karena tidak ada siswa yang memperoleh nilai tersebut, tetapi kita masih membutuhkan atribut tersebut karena model dilatih dengan semua atribut termasuk nilai tersebut. Syntax berikut ini membantu kita mengidentifikasi dan menambahkan fitur kategorikal yang hilang. Kita menambahkan nilai untuk setiap fitur tersebut sebagai 0 untuk setiap siswa karena mereka tidak mendapatkan nilai tersebut.

Syntax Python di bawah bertujuan memastikan kelengkapan fitur kategorikal dalam data baru untuk prediksi.

Prosesnya:

1.   Menentukan Fitur Kategorikal Saat Ini:current_categorical_engineered_features = set(prediction_features.columns) - set(numeric_feature_names) mengidentifikasi fitur kategorikal yang sudah ada dalam prediction_features dengan mengurangkan kolom numerik dari seluruh kolom.
2.   Mengidentifikasi Fitur Kategorikal yang Hilang: missing_features = set(categorical_engineered_features) - current_categorical_engineered_features menentukan fitur kategorikal mana yang seharusnya ada namun belum terdapat dalam prediction_features.
3. Menambahkan Fitur Hilang:
Loop for feature in missing_features:
Menambahkan kolom baru dengan nama feature ke dalam prediction_features.
Dan mengisi kolom tersebut dengan nilai 0 untuk seluruh baris data, karena fitur tersebut tidak ada di data baru.
4. Tampilan Akhir
prediction_features menampilkan DataFrame yang telah diperbarui dengan semua fitur kategorikal yang diperlukan untuk prediksi, termasuk yang sebelumnya tidak ada dalam data baru

Langkah ini penting untuk mencegah error akibat ketidaksesuaian dimensi fitur antara data latih dan data prediksi.

In [ ]:
# add missing categorical feature columns
current_categorical_engineered_features = set(prediction_features.columns) - set(numeric_feature_names)
missing_features = set(categorical_engineered_features) - current_categorical_engineered_features
for feature in missing_features:
    # add zeros since feature is absent in these data samples
    prediction_features[feature] = [0] * len(prediction_features)

# view final feature set
prediction_features

,ResearchScore,ProjectScore,OverallGrade_A,OverallGrade_F,Obedient_N,Obedient_Y,OverallGrade_B,OverallGrade_E,OverallGrade_C
0,-1.127647,-1.430636,0,1,1,0,0,0,0
1,0.494137,1.160705,1,0,0,1,0,0,0

Kita memiliki serangkaian fitur lengkap yang siap untuk kedua siswa baru. Mari kita uji model kami dan mendapatkan prediksi terkait rekomendasi beasiswa

Syntax Python di bawah, tahapan terakhir dari persiapan data dilakukan untuk memastikan bahwa fitur-fitur yang digunakan untuk melatih model sesuai dengan fitur-fitur yang ada dalam data prediksi.

Dengan proses:


1.   Mencocokan Fitur:
Bagian pertama memastikan bahwa data baru hanya berisi fitur yang digunakan saat melatih model.
prediction_features=prediction_features[training_features.columns] memilih fitur yang relevan dari data baru (prediction_features) berdasarkan fitur yang digunakan untuk melatih model (training_features.columns).
prediction_features.columns=training_features.columns mencocokkan nama kolom pada data baru dengan nama kolom pada data training untuk konsistensi.

2.    Menangani Fitur yang Hilang:
*   Kode memeriksa apakah ada fitur yang ada pada data training tetapi tidak ditemukan pada data baru.
missing_features=set(training_features.columns)-set(prediction_features.columns) membuat daftar fitur yang hilang.
*   Jika ada fitur yang hilang:
Looping iterasi melalui setiap fitur yang hilang (feature).
Kolom baru dengan nama fitur yang hilang ditambahkan ke prediction_features.
Kolom baru diisi dengan nilai 0 (prediction_features[feature]=0) untuk menunjukkan tidak adanya data untuk fitur tersebut.

3. Membuat Prediksi:
Terakhir, kode menggunakan model yang sudah terlatih (model) untuk membuat prediksi pada data baru yang telah disiapkan (prediction_features).
prediction=model.predict(prediction_features) menghasilkan prediksi untuk setiap data baru.

Syntax ini penting untuk memastikan kompatibilitas antara data baru dan data yang digunakan untuk melatih model. Hal ini membantu mencegah kesalahan prediksi dan menghasilkan perkiraan yang lebih akurat.

In [ ]:
prediction_features=prediction_features[training_features.columns]
prediction_features.columns=training_features.columns

missing_features=set(training_features.columns)-set(prediction_features.columns)
if missing_features :
  for feature in missing_features :
    prediction_features[feature]=0

    prediction=model.predict(prediction_features)

Syntax Python di bawah berfokus pada pembuatan prediksi dan menampilkan hasil.

Penjelasan:


1.   Prediksi:
predictions = model.predict(prediction_features) menggunakan model yang telah dilatih (model) untuk menghasilkan prediksi probabilitas untuk setiap baris data di prediction_features.

2.   Menampilkan Hasil:


*   new_data['Recommend'] = predictions menambahkan kolom baru bernama "Recommend" ke DataFrame new_data. Kolom ini berisi prediksi probabilitas yang dihasilkan.

*   new_data menampilkan DataFrame yang diperbarui dengan kolom "Recommend", menunjukkan prediksi untuk setiap siswa baru.

Secara keseluruhan, kode ini menghasilkan prediksi untuk data baru dan menambahkannya ke DataFrame yang sama untuk analisis dan interpretasi yang mudah.

In [ ]:
## predict using model
predictions = model.predict(prediction_features)

## display results
new_data['Recommend'] = predictions
new_data

     Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0  Nathan            F        N             30            20        No
1  Thomas            A        Y             78            80       Yes

Output syntax Python di atas menunjukkan nilai yang lebih tinggi pada kolom "Rekomendasi" menunjukkan kemungkinan yang lebih tinggi untuk direkomendasikan. Seperti, Thomas memiliki nilai keseluruhan A, patuh, skor riset 78, dan skor proyek 80, sehingga prediksinya 0.95, menunjukkan kemungkinan yang tinggi untuk direkomendasikan.

Sebaliknya, Nathan memiliki nilai keseluruhan F, tidak patuh, skor riset 30, dan skor proyek 20, sehingga prediksinya 0.12, menunjukkan kemungkinan yang rendah untuk direkomendasikan.